version: "3.8"

services:
  backend:
    stdin_open: true
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    volumes:
      - .:/app/
      - "/node_modules"
    tty: true

  #Contenedor de redis
  db:
    stdin_open: true
    image: redis
    ports:
      - "6379:6379"
    tty: true
